name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  web:
    name: Web Application Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: laravel_vue/src

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.1"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: laravel_vue/src/package-lock.json

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Composer Install
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Npm Install
        run: npm ci

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run ESLint
        run: npm run eslint

      - name: Build
        run: npm run build

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Run PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit

  app:
    name: Flutter Test
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: flutter_src

    steps:
      - name: Checkout
        uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: "3.3.9"

      - name: Check Version
        run: flutter --version

      - name: Install Packages
        run: flutter pub get

      - name: Copy env
        run: cp .env.example .env

      - name: Run Linter
        run: flutter analyze

      - name: Run Test
        run: flutter test
